/**
 * Strategy Constraints - Prevent generation of invalid strategies
 *
 * These constraints ensure that strategies generated by the GA are within
 * realistic operational bounds BEFORE simulation runs.
 */

import type { Strategy } from '../simulation/types.js';

/**
 * Strategy Parameter Bounds - Hard limits on what the GA can generate
 */
export const STRATEGY_BOUNDS = {
  // MCE Allocation: Custom line needs minimum capacity to meet 7-day delivery target
  // With 25-32 custom orders/day and MCE capacity of 30 units/day/machine:
  // Need at least 25/30 = 83% of 1 machine = 0.83, but use 0.3 minimum to allow optimization
  mceAllocationCustom: { min: 0.30, max: 0.85 }, // Give custom 30-85% of MCE capacity

  // Standard Pricing: Must be profitable but not price ourselves out of market
  standardPrice: { min: 400, max: 1200 }, // Below $400 likely unprofitable, above $1200 no demand

  // Overtime: Limited by business case
  dailyOvertimeHours: { min: 0, max: 4 }, // 0-4 hours per day allowed

  // Custom Pricing: Keep near data-driven values
  customBasePrice: { min: 90, max: 120 }, // Near regression baseline of $106.56
  customPenaltyPerDay: { min: 0.20, max: 0.35 }, // Near regression slope of $0.27
  customTargetDeliveryDays: { min: 5, max: 7 }, // Target 5-7 days delivery

  // Demand Model: Keep near historical data
  customDemandMean1: { min: 20, max: 30 }, // Phase 1 mean
  customDemandStdDev1: { min: 3, max: 8 }, // Phase 1 std dev
  customDemandMean2: { min: 28, max: 38 }, // Phase 2 mean (30% increase)
  customDemandStdDev2: { min: 4, max: 10 }, // Phase 2 std dev

  // Standard Demand: Keep near user input
  standardDemandIntercept: { min: 400, max: 600 }, // Near 500
  standardDemandSlope: { min: -0.35, max: -0.15 }, // Near -0.25

  // Quit Risk Model: Keep near business case
  overtimeTriggerDays: { min: 3, max: 7 }, // 3-7 consecutive days
  dailyQuitProbability: { min: 0.05, max: 0.20 }, // 5-20% quit chance
} as const;

/**
 * Apply bounds to a strategy parameter
 */
export function applyBound<T extends keyof typeof STRATEGY_BOUNDS>(
  param: T,
  value: number
): number {
  const bounds = STRATEGY_BOUNDS[param];
  return Math.max(bounds.min, Math.min(bounds.max, value));
}

/**
 * Constrain a strategy to valid bounds
 */
export function constrainStrategy(strategy: Strategy): Strategy {
  return {
    ...strategy,
    mceAllocationCustom: applyBound('mceAllocationCustom', strategy.mceAllocationCustom),
    standardPrice: applyBound('standardPrice', strategy.standardPrice),
    dailyOvertimeHours: applyBound('dailyOvertimeHours', strategy.dailyOvertimeHours),
    customBasePrice: applyBound('customBasePrice', strategy.customBasePrice),
    customPenaltyPerDay: applyBound('customPenaltyPerDay', strategy.customPenaltyPerDay),
    customTargetDeliveryDays: applyBound('customTargetDeliveryDays', strategy.customTargetDeliveryDays),
    customDemandMean1: applyBound('customDemandMean1', strategy.customDemandMean1),
    customDemandStdDev1: applyBound('customDemandStdDev1', strategy.customDemandStdDev1),
    customDemandMean2: applyBound('customDemandMean2', strategy.customDemandMean2),
    customDemandStdDev2: applyBound('customDemandStdDev2', strategy.customDemandStdDev2),
    standardDemandIntercept: applyBound('standardDemandIntercept', strategy.standardDemandIntercept),
    standardDemandSlope: applyBound('standardDemandSlope', strategy.standardDemandSlope),
    overtimeTriggerDays: applyBound('overtimeTriggerDays', strategy.overtimeTriggerDays),
    dailyQuitProbability: applyBound('dailyQuitProbability', strategy.dailyQuitProbability),
  };
}

/**
 * Validate strategy parameters before simulation
 * Returns true if strategy is within acceptable bounds
 */
export function isValidStrategy(strategy: Strategy): boolean {
  // Check all numeric parameters are within bounds
  for (const [param, bounds] of Object.entries(STRATEGY_BOUNDS)) {
    const value = strategy[param as keyof Strategy] as number;
    if (value < bounds.min || value > bounds.max) {
      console.warn(`Strategy parameter ${param} = ${value} outside bounds [${bounds.min}, ${bounds.max}]`);
      return false;
    }
  }

  // Additional business logic constraints
  // Custom demand phase 2 should be higher than phase 1 (market growth)
  if (strategy.customDemandMean2 < strategy.customDemandMean1) {
    console.warn('Custom demand phase 2 should be >= phase 1 (market growth)');
    return false;
  }

  // Standard demand slope must be negative (downward sloping demand curve)
  if (strategy.standardDemandSlope >= 0) {
    console.warn('Standard demand slope must be negative (price sensitivity)');
    return false;
  }

  // MCE allocation to custom should leave enough for standard line
  // Standard needs at least 15% to maintain minimum production
  if (strategy.mceAllocationCustom > 0.85) {
    console.warn('MCE allocation to custom too high, standard line would starve');
    return false;
  }

  return true;
}

/**
 * Generate a random strategy within valid bounds
 */
export function generateBoundedRandomStrategy(): Strategy {
  const strategy: Strategy = {
    // FORMULA-DRIVEN POLICIES: Set to 0, will be calculated dynamically
    reorderPoint: 0,
    orderQuantity: 0,
    standardBatchSize: 0,

    // GA-OPTIMIZABLE POLICIES: Random within bounds
    mceAllocationCustom:
      STRATEGY_BOUNDS.mceAllocationCustom.min +
      Math.random() * (STRATEGY_BOUNDS.mceAllocationCustom.max - STRATEGY_BOUNDS.mceAllocationCustom.min),

    standardPrice:
      STRATEGY_BOUNDS.standardPrice.min +
      Math.floor(Math.random() * (STRATEGY_BOUNDS.standardPrice.max - STRATEGY_BOUNDS.standardPrice.min)),

    dailyOvertimeHours: Math.floor(
      Math.random() * (STRATEGY_BOUNDS.dailyOvertimeHours.max + 1)
    ),

    // FIXED MARKET CONDITIONS: Use middle of allowed range
    customBasePrice: 106.56, // Data-driven baseline
    customPenaltyPerDay: 0.27, // Data-driven slope
    customTargetDeliveryDays: 5, // Target 5 days (within 7-day hard limit)

    // FIXED DEMAND MODEL: Use middle of allowed range
    customDemandMean1: 25,
    customDemandStdDev1: 5,
    customDemandMean2: 32.5, // 30% increase from phase 1
    customDemandStdDev2: 6.5,

    // FIXED STANDARD DEMAND CURVE
    standardDemandIntercept: 500,
    standardDemandSlope: -0.25,

    // FIXED QUIT RISK MODEL
    overtimeTriggerDays: 5,
    dailyQuitProbability: 0.10,

    // Timed actions (evolved by GA)
    timedActions: [],
  };

  return strategy;
}
